version: "3.8"

services:
  database:
    image: postgres
    container_name: "my-career-dev_database"
    volumes:
      - ./data/dev-database.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
